<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace OpenAiIntegration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openAiIntegration.GetMessagesParams</code>
 */
class GetMessagesParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 PromptId = 1;</code>
     */
    protected $PromptId = 0;
    /**
     * Generated from protobuf field <code>uint32 Limit = 2;</code>
     */
    protected $Limit = 0;
    /**
     * Generated from protobuf field <code>uint32 Offset = 3;</code>
     */
    protected $Offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $PromptId
     *     @type int $Limit
     *     @type int $Offset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 PromptId = 1;</code>
     * @return int
     */
    public function getPromptId()
    {
        return $this->PromptId;
    }

    /**
     * Generated from protobuf field <code>uint32 PromptId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPromptId($var)
    {
        GPBUtil::checkUint32($var);
        $this->PromptId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 Limit = 2;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * Generated from protobuf field <code>uint32 Limit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->Limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 Offset = 3;</code>
     * @return int
     */
    public function getOffset()
    {
        return $this->Offset;
    }

    /**
     * Generated from protobuf field <code>uint32 Offset = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkUint32($var);
        $this->Offset = $var;

        return $this;
    }

}

