<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace OpenAiIntegration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *результат выполнения метода GetPromptList
 *
 * Generated from protobuf message <code>openAiIntegration.GetPromptListResult</code>
 */
class GetPromptListResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .openAiIntegration.Prompt Result = 1;</code>
     */
    private $Result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\OpenAiIntegration\Prompt>|\Google\Protobuf\Internal\RepeatedField $Result
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .openAiIntegration.Prompt Result = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResult()
    {
        return $this->Result;
    }

    /**
     * Generated from protobuf field <code>repeated .openAiIntegration.Prompt Result = 1;</code>
     * @param array<\OpenAiIntegration\Prompt>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResult($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \OpenAiIntegration\Prompt::class);
        $this->Result = $arr;

        return $this;
    }

}

