<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace OpenAiIntegration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>openAiIntegration.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     */
    protected $Id = 0;
    /**
     * Generated from protobuf field <code>uint32 UserId = 2;</code>
     */
    protected $UserId = 0;
    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     */
    protected $Message = '';
    /**
     * Generated from protobuf field <code>uint32 PromptId = 4;</code>
     */
    protected $PromptId = 0;
    /**
     * Generated from protobuf field <code>string SubPrompt = 5;</code>
     */
    protected $SubPrompt = '';
    /**
     * Generated from protobuf field <code>string CreateDate = 6;</code>
     */
    protected $CreateDate = '';
    /**
     * Generated from protobuf field <code>uint32 TokenCost = 7;</code>
     */
    protected $TokenCost = 0;
    /**
     * Generated from protobuf field <code>string Response = 8;</code>
     */
    protected $Response = '';
    /**
     * Generated from protobuf field <code>string Uuid = 9;</code>
     */
    protected $Uuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *     @type int $UserId
     *     @type string $Message
     *     @type int $PromptId
     *     @type string $SubPrompt
     *     @type string $CreateDate
     *     @type int $TokenCost
     *     @type string $Response
     *     @type string $Uuid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 UserId = 2;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * Generated from protobuf field <code>uint32 UserId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint32($var);
        $this->UserId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 PromptId = 4;</code>
     * @return int
     */
    public function getPromptId()
    {
        return $this->PromptId;
    }

    /**
     * Generated from protobuf field <code>uint32 PromptId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPromptId($var)
    {
        GPBUtil::checkUint32($var);
        $this->PromptId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SubPrompt = 5;</code>
     * @return string
     */
    public function getSubPrompt()
    {
        return $this->SubPrompt;
    }

    /**
     * Generated from protobuf field <code>string SubPrompt = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSubPrompt($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubPrompt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string CreateDate = 6;</code>
     * @return string
     */
    public function getCreateDate()
    {
        return $this->CreateDate;
    }

    /**
     * Generated from protobuf field <code>string CreateDate = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCreateDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreateDate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 TokenCost = 7;</code>
     * @return int
     */
    public function getTokenCost()
    {
        return $this->TokenCost;
    }

    /**
     * Generated from protobuf field <code>uint32 TokenCost = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setTokenCost($var)
    {
        GPBUtil::checkUint32($var);
        $this->TokenCost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Response = 8;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->Response;
    }

    /**
     * Generated from protobuf field <code>string Response = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, True);
        $this->Response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Uuid = 9;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->Uuid;
    }

    /**
     * Generated from protobuf field <code>string Uuid = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->Uuid = $var;

        return $this;
    }

}

