<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace OpenAiIntegration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *параметры для отправки сообщения в openAI
 *
 * Generated from protobuf message <code>openAiIntegration.SendMessageParams</code>
 */
class SendMessageParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 PromptId = 1;</code>
     */
    protected $PromptId = 0;
    /**
     * Generated from protobuf field <code>string SubPromptName = 2;</code>
     */
    protected $SubPromptName = '';
    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     */
    protected $Message = '';
    /**
     * Generated from protobuf field <code>uint32 ModelId = 4;</code>
     */
    protected $ModelId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $PromptId
     *     @type string $SubPromptName
     *     @type string $Message
     *     @type int $ModelId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 PromptId = 1;</code>
     * @return int
     */
    public function getPromptId()
    {
        return $this->PromptId;
    }

    /**
     * Generated from protobuf field <code>uint32 PromptId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPromptId($var)
    {
        GPBUtil::checkUint32($var);
        $this->PromptId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string SubPromptName = 2;</code>
     * @return string
     */
    public function getSubPromptName()
    {
        return $this->SubPromptName;
    }

    /**
     * Generated from protobuf field <code>string SubPromptName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubPromptName($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubPromptName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * Generated from protobuf field <code>string Message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 ModelId = 4;</code>
     * @return int
     */
    public function getModelId()
    {
        return $this->ModelId;
    }

    /**
     * Generated from protobuf field <code>uint32 ModelId = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setModelId($var)
    {
        GPBUtil::checkUint32($var);
        $this->ModelId = $var;

        return $this;
    }

}

